version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    rebase-strategy: auto
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "04:00"
