language: python
sudo: false
branches:
  only:
  - master
cache:
- pip
- apt
python:
- '3.8-dev'
services:
- redis-server
install:
- pip install -U pipenv
- pipenv install --dev
script:
- pipenv run coverage run --source=stanley -m 'pytest'
after_success: codecov
