language: python
sudo: false
branches:
  only:
  - master
cache:
- pip
- apt
python:
- '3.6'
services:
- redis-server
install:
- pip install -U pipenv
- pipenv install --dev
script:
- pipenv run pytest
after_success: codecov
